openapi: 3.0.1
info:
  title: ProEventIQ Rest API
  description: API for ProEventIQ
  version: "0.15"
servers:
  - url: http://{hostname}:{port}/api
    variables:
      hostname:
        default: localhost
      port:
        enum:
          - "8080"
          - "443"
        default: "8080"
tags:
  - name: ProEventIQ
    description: ProEventIQ endpoints

paths:
  /venues:
    $ref: './venue/venue-controller.yaml#/venues'
  /venues/{venueId}:
    $ref: './venue/venue-controller.yaml#/venueById'
  /venues/{venueId}/sectors:
    $ref: './sector/sector-controller.yaml#/sectorsByVenue'
  /venues/{venueId}/sectors/{sectorId}:
    $ref: './sector/sector-controller.yaml#/sectorById'
  /venues/{venueId}/sectors/{sectorId}/seats:
    $ref: './sector/sector-controller.yaml#/sectorLayout'
  /shows:
    $ref: './show/show-controller.yaml#/shows'
  /shows/{showId}:
    $ref: './show/show-controller.yaml#/showById'