openapi: 3.0.1
info:
  title: ProEventIQ Rest API
  description: API for ProEventIQ
  version: "0.4"
servers:
  - url: http://{hostname}:{port}/api
    variables:
      hostname:
        default: localhost
      port:
        enum:
          - "8080"
          - "443"
        default: "8080"
tags:
  - name: ProEventIQ
    description: ProEventIQ endpoints

paths:
  /venues:
    $ref: './venue/venue-controller.yaml#/venues'
  /venues/{venueId}:
    $ref: './venue/venue-controller.yaml#/venueById'
  /venues/{venueId}/sectors:
    $ref: './sector/sector-controller.yaml#/sectorsByVenue'
  /sectors/{sectorId}:
    $ref: './sector/sector-controller.yaml#/sectorById'
  /sectors/{sectorId}/rows:
    $ref: './sector/sector-controller.yaml#/rowsBySector'
  /rows/{rowId}:
    $ref: './seat/seat-controller.yaml#/seatRowById'
  /rows/{rowId}/seats:
    $ref: './seat/seat-controller.yaml#/seatsBySeatRow'
  /seats/{seatId}:
    $ref: './seat/seat-controller.yaml#/seatById'